services:
  ai_abcs:
    #build: .
    image: nben/aiabcs:2026-03-02
    ports:
      - "${AIABCS_PORT:-8888}:${AIABCS_PORT:-8888}"
    environment:
      JUPYTER_PORT: "${AIABCS_PORT:-8888}"
      DOCKER_STACKS_JUPYTER_CMD: "${AIABCS_MODE:-lab}"
    volumes:
      - "${PWD}:/home/jovyan/repo"
