###############################################################################
# tests.yml
#
# GitHub Actions Workflow for testing the build process for the AI ABCs
# website.
# This is largely a modified version of the template given by the Jupyter book
# project, here:
# https://jupyterbook.org/en/stable/publish/gh-pages.html
#
# by Noah C. Benson

name: Test Website Build

on:
  push:
    branches:
      - main
    paths:
      - lessons/**
      - requirements.txt
      - .github/workflows/tests.yml
  workflow_dispatch:
    
jobs:
  test-website:
    name: Test Website Build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment: github-pages
    steps:
      - uses: actions/checkout@v4
      # Install dependencies
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: pip # Implicitly uses requirements.txt for cache key
      - name: Install all relevant libraries
        run: pip install -r requirements.txt
      # Test things (i.e., build the book)
      - name: Build Website
        run: |
          mkdir -p site
          jupyter-book build --path-output site lessons
